# Generated by Django 4.1.7 on 2024-01-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0002_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
